[package]
name = "smth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
clap = { version = "3.0.0-rc.7", features = ["derive"] }
colored = "2"   
ansi_term = "0.12.1"